exports.TXN_VECTOR_BATCH_SIZE 		= 5000
exports.TXN_ID_BATCH_SIZE 			= 1000
exports.MIN_SEQUENCE_SIZE 			= 3
exports.MAX_SEQUENCE_SIZE 			= 8
exports.MIN_SEQUENCE_FREQUENCY 		= 8
exports.NUM_CENTROIDS			 	= 50